### ISSUE TITLE
fun nas sync PHP7.2 laravel6 时报错

### ISSUE THREAD

**Issue by 0758jian** [alibaba/funcraft#1085]
:unzipping █████████████████████ 1241/7656 1666 files/s, 16% 0.7 sError: Command failed: unzip -q -o /mnt/demo/.fun_nas_tmp/.fun-nas-generated-fc-shining.zip -d /mnt/demo/ 'vendor/composer/composer/doc/faqs/why-can't-composer-load-repositories-recursively.md'
/bin/sh: 1: Syntax error: Unterminated quoted string

    at /snapshot/funcraft/lib/nas/request.js:47:19
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/funcraft/lib/nas/request.js:4:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Unzip error! Please re-sync.

#### 尝试windows和linux 环境同步操作都是报上面位置的错误，不解一个md文件为什么会解压出错？

**Comment by 0758jian** [comment]
我留意到文件名有类似单引号 ’
why-can't-composer-load-repositories-recursively.md
但vendor是composer安装，难道要我手工改名？
