### ISSUE TITLE
Install error on Ubuntu

### ISSUE THREAD

**Issue by leinue** [alibaba/funcraft#341]
Node 版本： `v9.4.0`

在 docker 中安装的，镜像使用的 `node:9`，安装失败（同样的镜像在 OSX 中成功）：
 @tanhe123 请看一下，谢谢

```shell
npm ERR! Unexpected end of JSON input while parsing near '...st":{"integrity":"sha'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-14T01_24_39_433Z-debug.log
3Z-debug.logrvice_in_container:/app# cat /root/.npm/_logs/2019-08-14T01_24_39_43 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@alicloud/fun',
1 verbose cli   '-g' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session 4e74469e4235bb5e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@alicloud%2ffun 1423ms (from cache)
8 silly pacote tag manifest for @alicloud/fun@latest fetched in 1708ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @alicloud/fun@2.16.3 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/@alicloud%2ffc 556ms (from cache)
15 silly pacote range manifest for @alicloud/fc@^1.2.3 fetched in 560ms
16 silly resolveWithNewModule @alicloud/fc@1.2.3 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/async-lock 749ms (from cache)
18 silly pacote range manifest for async-lock@^1.1.4 fetched in 753ms
19 silly resolveWithNewModule async-lock@1.2.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/archiver 757ms (from cache)
21 silly pacote range manifest for archiver@^2.0.0 fetched in 762ms
22 silly resolveWithNewModule archiver@2.1.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/ci-info 240ms (from cache)
24 silly pacote range manifest for ci-info@^2.0.0 fetched in 243ms
25 silly resolveWithNewModule ci-info@2.0.0 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/@alicloud%2fpop-core 821ms (from cache)
27 silly pacote range manifest for @alicloud/pop-core@^1.6.0 fetched in 824ms
28 silly resolveWithNewModule @alicloud/pop-core@1.7.7 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/command-exists 212ms (from cache)
30 silly pacote range manifest for command-exists@^1.2.8 fetched in 216ms
31 silly resolveWithNewModule command-exists@1.2.8 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/commander 219ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/colors 257ms (from cache)
34 silly pacote range manifest for commander@^2.15.1 fetched in 223ms
35 silly resolveWithNewModule commander@2.20.0 checking installable status
36 silly pacote range manifest for colors@^1.1.2 fetched in 265ms
37 silly resolveWithNewModule colors@1.3.3 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/conf 228ms (from cache)
39 silly pacote range manifest for conf@^4.0.2 fetched in 241ms
40 silly resolveWithNewModule conf@4.1.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/@alicloud%2fcloudapi 1085ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/@alicloud%2fmns 1083ms (from cache)
43 silly pacote range manifest for @alicloud/cloudapi@^1.0.0 fetched in 1103ms
44 silly resolveWithNewModule @alicloud/cloudapi@1.1.0 checking installable status
45 silly pacote range manifest for @alicloud/mns@^1.0.0 fetched in 1089ms
46 silly resolveWithNewModule @alicloud/mns@1.0.0 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/@alicloud%2ffc2 1166ms (from cache)
48 silly pacote range manifest for @alicloud/fc2@^2.1.0 fetched in 1177ms
49 silly resolveWithNewModule @alicloud/fc2@2.1.1 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/crc64-ecma182.js 228ms (from cache)
51 silly pacote range manifest for crc64-ecma182.js@^1.0.0 fetched in 242ms
52 silly resolveWithNewModule crc64-ecma182.js@1.0.0 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/detect-mocha 210ms (from cache)
54 silly pacote range manifest for detect-mocha@^0.1.0 fetched in 212ms
55 silly resolveWithNewModule detect-mocha@0.1.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/dev-null 211ms (from cache)
57 silly pacote range manifest for dev-null@^0.1.1 fetched in 213ms
58 silly resolveWithNewModule dev-null@0.1.1 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/dockerode 209ms (from cache)
60 silly pacote range manifest for dockerode@^2.5.7 fetched in 214ms
61 silly resolveWithNewModule dockerode@2.5.8 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/dotenv 240ms (from cache)
63 silly pacote range manifest for dotenv@^6.0.0 fetched in 244ms
64 silly resolveWithNewModule dotenv@6.2.0 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/es6-promise-pool 249ms (from cache)
66 silly pacote range manifest for es6-promise-pool@^2.5.0 fetched in 267ms
67 silly resolveWithNewModule es6-promise-pool@2.5.0 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/ajv 1451ms (from cache)
69 silly pacote range manifest for ajv@^6.4.0 fetched in 1460ms
70 silly resolveWithNewModule ajv@6.10.2 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/findit2 233ms (from cache)
72 silly pacote range manifest for findit2@^2.2.3 fetched in 236ms
73 silly resolveWithNewModule findit2@2.2.3 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/express 273ms (from cache)
75 silly pacote range manifest for express@^4.16.4 fetched in 288ms
76 silly resolveWithNewModule express@4.17.1 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/fs-extra 246ms (from cache)
78 http fetch GET 304 https://registry.npmjs.org/get-stdin 225ms (from cache)
79 silly pacote range manifest for fs-extra@^8.1.0 fetched in 249ms
80 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
81 silly pacote range manifest for get-stdin@^6.0.0 fetched in 229ms
82 silly resolveWithNewModule get-stdin@6.0.0 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/git-ignore-parser 222ms (from cache)
84 silly pacote version manifest for git-ignore-parser@0.0.2 fetched in 226ms
85 silly resolveWithNewModule git-ignore-parser@0.0.2 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/glob 215ms (from cache)
87 http fetch GET 304 https://registry.npmjs.org/@alicloud%2fram 1650ms (from cache)
88 silly pacote range manifest for glob@^7.1.2 fetched in 221ms
89 silly resolveWithNewModule glob@7.1.4 checking installable status
90 silly pacote range manifest for @alicloud/ram@^1.0.0 fetched in 1654ms
91 silly resolveWithNewModule @alicloud/ram@1.0.0 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/http-string-parser 216ms (from cache)
93 http fetch GET 304 https://registry.npmjs.org/@alicloud%2flog 1680ms (from cache)
94 silly pacote version manifest for http-string-parser@0.0.6 fetched in 220ms
95 silly resolveWithNewModule http-string-parser@0.0.6 checking installable status
96 silly pacote range manifest for @alicloud/log@^1.1.0 fetched in 1690ms
97 silly resolveWithNewModule @alicloud/log@1.2.0 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/debug 698ms (from cache)
99 silly pacote range manifest for debug@^2.6.8 fetched in 706ms
100 silly resolveWithNewModule debug@2.6.9 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/ignore 219ms (from cache)
102 silly pacote range manifest for ignore@^5.0.4 fetched in 227ms
103 silly resolveWithNewModule ignore@5.1.2 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/inquirer-autocomplete-prompt 226ms (from cache)
105 silly pacote range manifest for inquirer-autocomplete-prompt@^1.0.1 fetched in 229ms
106 silly resolveWithNewModule inquirer-autocomplete-prompt@1.0.1 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/ip 233ms (from cache)
108 silly pacote range manifest for ip@^1.1.5 fetched in 237ms
109 silly resolveWithNewModule ip@1.1.5 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/inquirer 303ms (from cache)
111 silly pacote range manifest for inquirer@^5.2.0 fetched in 308ms
112 silly resolveWithNewModule inquirer@5.2.0 checking installable status
113 http fetch GET 304 https://registry.npmjs.org/httpx 373ms (from cache)
114 silly pacote range manifest for httpx@^2.1.2 fetched in 378ms
115 silly resolveWithNewModule httpx@2.2.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/js-yaml 251ms (from cache)
117 silly pacote range manifest for js-yaml@^3.13.1 fetched in 255ms
118 silly resolveWithNewModule js-yaml@3.13.1 checking installable status
119 http fetch GET 304 https://registry.npmjs.org/kitx 223ms (from cache)
120 http fetch GET 304 https://registry.npmjs.org/jszip 231ms (from cache)
121 silly pacote range manifest for kitx@^1.2.1 fetched in 226ms
122 silly resolveWithNewModule kitx@1.3.0 checking installable status
123 silly pacote range manifest for jszip@^3.1.5 fetched in 239ms
124 silly resolveWithNewModule jszip@3.2.2 checking installable status
125 http fetch GET 304 https://registry.npmjs.org/lodash 228ms (from cache)
126 silly pacote range manifest for lodash@^4.17.11 fetched in 233ms
127 silly resolveWithNewModule lodash@4.17.15 checking installable status
128 http fetch GET 304 https://registry.npmjs.org/md5-file 218ms (from cache)
129 silly pacote range manifest for md5-file@^4.0.0 fetched in 223ms
130 silly resolveWithNewModule md5-file@4.0.0 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/memory-streams 241ms (from cache)
132 http fetch GET 304 https://registry.npmjs.org/json-colorizer 350ms (from cache)
133 silly pacote range manifest for json-colorizer@^2.2.0 fetched in 353ms
134 silly resolveWithNewModule json-colorizer@2.2.1 checking installable status
135 silly pacote range manifest for memory-streams@^0.1.3 fetched in 262ms
136 silly resolveWithNewModule memory-streams@0.1.3 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/nested-object-assign 214ms (from cache)
138 silly pacote range manifest for nested-object-assign@^1.0.3 fetched in 220ms
139 silly resolveWithNewModule nested-object-assign@1.0.3 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/node-machine-id 229ms (from cache)
141 http fetch GET 304 https://registry.npmjs.org/mkdirp-promise 265ms (from cache)
142 silly pacote range manifest for mkdirp-promise@^5.0.1 fetched in 278ms
143 silly resolveWithNewModule mkdirp-promise@5.0.1 checking installable status
144 silly pacote range manifest for node-machine-id@^1.1.10 fetched in 235ms
145 silly resolveWithNewModule node-machine-id@1.1.12 checking installable status
146 http fetch GET 304 https://registry.npmjs.org/node-watch 221ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/os-locale 222ms (from cache)
148 silly pacote range manifest for node-watch@^0.6.0 fetched in 224ms
149 silly resolveWithNewModule node-watch@0.6.3 checking installable status
150 silly pacote range manifest for os-locale@^2.1.0 fetched in 226ms
151 silly resolveWithNewModule os-locale@2.1.0 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/os-name 216ms (from cache)
153 silly pacote range manifest for os-name@^3.1.0 fetched in 225ms
154 silly resolveWithNewModule os-name@3.1.0 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/progress 252ms (from cache)
156 silly pacote range manifest for progress@^2.0.3 fetched in 254ms
157 silly resolveWithNewModule progress@2.0.3 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/raw-body 220ms (from cache)
159 silly pacote range manifest for raw-body@^2.3.3 fetched in 225ms
160 silly resolveWithNewModule raw-body@2.4.1 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/promise-retry 314ms (from cache)
162 http fetch GET 200 https://registry.npmjs.org/rimraf 243ms
163 silly pacote range manifest for promise-retry@^1.1.1 fetched in 321ms
164 silly resolveWithNewModule promise-retry@1.1.1 checking installable status
165 http fetch GET 304 https://registry.npmjs.org/semver 251ms (from cache)
166 http fetch GET 304 https://registry.npmjs.org/require-from-string 273ms (from cache)
167 silly pacote range manifest for rimraf@^2.6.2 fetched in 254ms
168 silly resolveWithNewModule rimraf@2.7.0 checking installable status
169 silly pacote range manifest for require-from-string@^2.0.2 fetched in 277ms
170 silly resolveWithNewModule require-from-string@2.0.2 checking installable status
171 silly pacote range manifest for semver@^5.5.0 fetched in 278ms
172 silly resolveWithNewModule semver@5.7.1 checking installable status
173 http fetch GET 304 https://registry.npmjs.org/single-line-log 292ms (from cache)
174 http fetch GET 304 https://registry.npmjs.org/split-file 290ms (from cache)
175 http fetch GET 304 https://registry.npmjs.org/supertest 256ms (from cache)
176 silly pacote range manifest for single-line-log@^1.1.2 fetched in 296ms
177 silly resolveWithNewModule single-line-log@1.1.2 checking installable status
178 silly pacote range manifest for split-file@^2.1.1 fetched in 294ms
179 silly resolveWithNewModule split-file@2.1.1 checking installable status
180 silly pacote range manifest for supertest@^4.0.2 fetched in 263ms
181 silly resolveWithNewModule supertest@4.0.2 checking installable status
182 http fetch GET 304 https://registry.npmjs.org/tablestore 222ms (from cache)
183 silly pacote range manifest for tablestore@^4.3.2 fetched in 226ms
184 silly resolveWithNewModule tablestore@4.3.2 checking installable status
185 http fetch GET 304 https://registry.npmjs.org/universal-analytics 278ms (from cache)
186 silly pacote range manifest for universal-analytics@^0.4.20 fetched in 284ms
187 silly resolveWithNewModule universal-analytics@0.4.20 checking installable status
188 http fetch GET 304 https://registry.npmjs.org/unzipper 259ms (from cache)
189 silly pacote range manifest for unzipper@^0.10.2 fetched in 267ms
190 silly resolveWithNewModule unzipper@0.10.3 checking installable status
191 http fetch GET 304 https://registry.npmjs.org/urlencode 256ms (from cache)
192 silly pacote range manifest for urlencode@^1.1.0 fetched in 266ms
193 silly resolveWithNewModule urlencode@1.1.0 checking installable status
194 http fetch GET 304 https://registry.npmjs.org/update-notifier 284ms (from cache)
195 http fetch GET 304 https://registry.npmjs.org/temp-dir 258ms (from cache)
196 silly pacote range manifest for update-notifier@^3.0.0 fetched in 293ms
197 silly resolveWithNewModule update-notifier@3.0.1 checking installable status
198 silly pacote range manifest for temp-dir@^1.0.0 fetched in 266ms
199 silly resolveWithNewModule temp-dir@1.0.0 checking installable status
200 http fetch GET 304 https://registry.npmjs.org/node-stream-zip 758ms (from cache)
201 silly pacote range manifest for node-stream-zip@^1.8.2 fetched in 761ms
202 silly resolveWithNewModule node-stream-zip@1.8.2 checking installable status
203 silly pacote range manifest for debug@^3.1.0 fetched in 55ms
204 silly resolveWithNewModule debug@3.2.6 checking installable status
205 http fetch GET 304 https://registry.npmjs.org/xml2js 217ms (from cache)
206 silly pacote range manifest for xml2js@^0.4.17 fetched in 220ms
207 silly resolveWithNewModule xml2js@0.4.19 checking installable status
208 http fetch GET 304 https://registry.npmjs.org/json-bigint 265ms (from cache)
209 silly pacote range manifest for json-bigint@^0.2.3 fetched in 269ms
210 silly resolveWithNewModule json-bigint@0.2.3 checking installable status
211 http fetch GET 304 https://registry.npmjs.org/ms 221ms (from cache)
212 silly pacote range manifest for ms@^2.1.1 fetched in 225ms
213 silly resolveWithNewModule ms@2.1.2 checking installable status
214 silly pacote range manifest for debug@^4.1.1 fetched in 3ms
215 silly resolveWithNewModule debug@4.1.1 checking installable status
216 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 288ms (from cache)
217 silly fetchPackageMetaData error for @types/node@^12.0.2 Unexpected end of JSON input while parsing near '...st":{"integrity":"sha'
218 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...st":{"integrity":"sha'
218 verbose stack     at JSON.parse (<anonymous>)
218 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
218 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
218 verbose stack     at <anonymous>
218 verbose stack     at process._tickCallback (internal/process/next_tick.js:160:7)
219 verbose cwd /app
220 verbose Linux 4.4.0-91-generic
221 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@alicloud/fun" "-g"
222 verbose node v9.4.0
223 verbose npm  v5.6.0
224 error Unexpected end of JSON input while parsing near '...st":{"integrity":"sha'
225 verbose exit [ 1, true ]

```

**Comment by leinue** [comment]
``` shell
npm cache clean -f
npm install @alicloud/fun -g
```
