### ISSUE TITLE
当 endpoint 设置成内网的时候，fun deploy 时报 api gateway 出错

### ISSUE THREAD

**Issue by joshle** [alibaba/funcraft#60]
```
> fun deploy
Waiting for service fc to be deployed...
	Waiting for function users to be deployed...
	function users deploy success
service fc deploy success

Waiting for api gateway HelloworldGroup to be deployed...
Error: getaddrinfo ENOTFOUND apigateway.cn-hangzhou-internal.aliyuncs.com apigateway.cn-hangzhou-internal.aliyuncs.com:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by tanhe123** [comment]
这个 endpoint 指的是 Fun 在您的机器上要访问的地址，如果您的机器在内网环境，那么可以使用内网地址，否则，不可以。

**Comment by joshle** [comment]
我的机器是杭州的 ECS，满足内网环境的才对

**Comment by tanhe123** [comment]
您在机器上 ping 一下这个地址试下 apigateway.cn-hangzhou-internal.aliyuncs.com

**Comment by joshle** [comment]
是 ping 不同，但是函数是可行的，我的函数比较大（100M），用内网的地址可以很快上传，改外网，就提示上传超时了。

```
> cat ~/.fcli/config.yaml 
endpoint: 'https://1396422.cn-hangzhou.fc.aliyuncs.com'
# endpoint: 'https://1396422.cn-hangzhou-internal.fc.aliyuncs.com'
...
```

**Comment by joshle** [comment]
是 ping 不通，但是函数是可行的，我的函数比较大（100M），用内网的地址可以很快上传，改外网，就提示上传超时了。

```
> cat ~/.fcli/config.yaml 
endpoint: 'https://139***.cn-hangzhou.fc.aliyuncs.com'
# endpoint: 'https://139***.cn-hangzhou-internal.fc.aliyuncs.com'
...
```

**Comment by joshle** [comment]
是不是有专门像 sls endpoint 的配置项：

```
sls_endpoint: cn-hangzhou.log.aliyuncs.com
```

**Comment by tanhe123** [comment]
上传超时的报错方便贴一下吗？

**Comment by tanhe123** [comment]
> 是不是有专门像 sls endpoint 的配置项：
> sls_endpoint: cn-hangzhou.log.aliyuncs.com

很遗憾，目前还没有

**Comment by tanhe123** [comment]
可以先走 oss，在 CodeUri 支持 oss，写法为：

`CodeUri: 'oss://my-fc-testt/2018/helloworld.zip'`

**Comment by joshle** [comment]
那我觉得 如果 apigateway 不支持内网 endpoint ，就不要去配置成内网的就可以了，不影响函数代码通过内网上传

**Comment by joshle** [comment]
>  上传超时的报错方便贴一下吗？

```
  lambda request headers: {"accept":"application/json","date":"Tue, 10 Jul 2018 14:35:35 GMT","host":"******.cn-hangzhou.fc.aliyuncs.com","user-agent":"@alicloud/fun/v2.1.0 ( Node.js v8.9.0; OS linux x64; language en_US )","x-fc-account-id":"******","content-type":"application/json","content-length":50482230,"content-md5":"ODFiMDNlMTUzMDdiNDAxMTc0Y2Q1N2JiZGZhOWRhNDY=","authorization":"FC LTAI2ZlWsNMJtxQ9:qHI8pl402F3vLBhhRmvaTupV8SwlO0JRQ9EWLTcgKeU="} +3ms
RequestTimeoutError: Timeout(60000). PUT http://******.cn-hangzhou.fc.aliyuncs.com/2016-08-15/services/***/functions failed.
    at Timeout.setTimeout [as _onTimeout] (/root/.nvm/versions/node/v8.9.0/lib/node_modules/@alicloud/fun/node_modules/.2.1.3@httpx/lib/index.js:109:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by joshle** [comment]
>  上传超时的报错方便贴一下吗？

```
  lambda request headers: {"accept":"application/json","date":"Tue, 10 Jul 2018 14:35:35 GMT","host":"******.cn-hangzhou.fc.aliyuncs.com","user-agent":"@alicloud/fun/v2.1.0 ( Node.js v8.9.0; OS linux x64; language en_US )","x-fc-account-id":"******","content-type":"application/json","content-length":50482230,"content-md5":"ODFiMDNlM******RhNDY=","authorization":"FC LTAI******:****eU="} +3ms
RequestTimeoutError: Timeout(60000). PUT http://******.cn-hangzhou.fc.aliyuncs.com/2016-08-15/services/***/functions failed.
    at Timeout.setTimeout [as _onTimeout] (/root/.nvm/versions/node/v8.9.0/lib/node_modules/@alicloud/fun/node_modules/.2.1.3@httpx/lib/index.js:109:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by joshle** [comment]
是不是提供一个 internal: true 这样子的开关配置项，然后支持内网的 endpoint 就走内网

**Comment by tanhe123** [comment]
如果还有类似需求，可以单独为 FC 配置 FC_ENDPOINT
