### ISSUE TITLE
fun install --runtime python3 --package-type pip flask_sqlalchemy 失败

### ISSUE THREAD

**Issue by Moonstarwork** [alibaba/funcraft#807]
flask_sqlalchemy安装失败，试了好几个电脑都一样，数据库orm的关键库，不用不行

**Comment by Moonstarwork** [comment]
```
PS E:\yankevip\project\function_compute> fun install --runtime python3 --package-type pip flask_sqlalchemy
skip pulling image aliyunfc/runtime-python3.6:build-1.9.2...
Task => PipTask
     => PYTHONUSERBASE=/code/.fun/python pip install --user flask_sqlalchemy
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting flask_sqlalchemy
  Downloading http://mirrors.aliyun.com/pypi/packages/1e/65/226d95466c75e34e291a76890ed0e27af2e46ab913002847856f11d4d59d/Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: Flask>=0.10 in ./.fun/python/lib/python3.6/site-packages (from flask_sqlalchemy) (1.1.1)
Collecting SQLAlchemy>=0.8.0
  Downloading http://mirrors.aliyun.com/pypi/packages/8c/30/4134e726dd5ed13728ff814fa91fc01c447ad8700504653fe99d91fdd34b/SQLAlchemy-1.3.15.tar.gz (6.1 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lzepifsa/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/usr/local/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/usr/local/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lzepifsa/overlay --no-warn-script-location --no-binary :none: --only-binary :none: 
-i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel Check the logs for full 
command output.
undefined
```

**Comment by coco-super** [comment]
@Moonstarwork 测试了 mac 和 windows 都未出现问题，请用最新版 fun 再次尝试，有问题提新的 issue。
