### ISSUE TITLE
[Bug] 无法在 Windows 环境下编译 funcraft

### ISSUE THREAD

**Issue by DevDengChao** [alibaba/funcraft#933]
```
11145 verbose stack Error: exited with error code: 128
11145 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\util\finished.js:12:19)
11145 verbose stack     at ChildProcess.emit (events.js:310:20)
11145 verbose stack     at maybeClose (internal/child_process.js:1021:16)
11145 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
11146 verbose cwd D:\workspace\nodejs\Funcraft
11147 verbose Windows_NT 10.0.18363
11148 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--scripts-prepend-node-path=auto"
11149 verbose node v12.16.3
11150 verbose npm  v6.14.4
11151 error Error while executing:
11151 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/aliyun/fc-nodejs-sdk.git
11151 error
11151 error fatal: read error: Invalid argument
11151 error
11151 error exited with error code: 128
11152 verbose exit [ 1, true ]
```

[2020-05-29T05_51_37_801Z-debug.log](https://github.com/alibaba/funcraft/files/4699921/2020-05-29T05_51_37_801Z-debug.log)

**Comment by XieEDeHeiShou** [comment]
git version 2.26.2.windows.1
node v12.16.3
npm 6.14.5

**Comment by coco-super** [comment]
@XieEDeHeiShou 上下文是什么，如何操作的？

**Comment by XieEDeHeiShou** [comment]
> @XieEDeHeiShou 上下文是什么，如何操作的？

在项目的根目录执行 `npm install` 时出现上述错误日志.

[npm-install.log](https://github.com/alibaba/funcraft/files/4728016/npm-install.log)

**Comment by DevDengChao** [comment]
已迁移到 @serverless-devs/s
