### ISSUE TITLE
fun local start 访问函数报错

### ISSUE THREAD

**Issue by CloudyAnt** [alibaba/funcraft#938]
执行 `fun build && fun local start` 后，访问函数，报如下错误：

```
skip pulling image aliyunfc/runtime-custom:1.9.5...
/usr/local/lib/node_modules/@alicloud/fun/node_modules/ignore/index.js:366
  throw new Ctor(message)
  ^

RangeError: path should be a `path.relative()`d string, but got "../../tmp/local/todomato-user-service/user-function/hsperfdata_user10003/23"
    at throwError (/usr/local/lib/node_modules/@alicloud/fun/node_modules/ignore/index.js:366:9)
    at checkPath (/usr/local/lib/node_modules/@alicloud/fun/node_modules/ignore/index.js:385:12)
    at Ignore._test (/usr/local/lib/node_modules/@alicloud/fun/node_modules/ignore/index.js:502:5)
    at Ignore.ignores (/usr/local/lib/node_modules/@alicloud/fun/node_modules/ignore/index.js:541:17)
    at /usr/local/lib/node_modules/@alicloud/fun/lib/package/ignore.js:50:23
    at filter (/usr/local/lib/node_modules/@alicloud/fun/lib/local/http-invoke.js:87:56)
    at /usr/local/lib/node_modules/@alicloud/fun/node_modules/node-watch/lib/watch.js:33:11
    at /usr/local/lib/node_modules/@alicloud/fun/node_modules/node-watch/lib/watch.js:303:7
    at /usr/local/lib/node_modules/@alicloud/fun/node_modules/node-watch/lib/watch.js:109:10
    at Array.forEach (<anonymous>)
    at Timeout.handle [as _onTimeout] (/usr/local/lib/node_modules/@alicloud/fun/node_modules/node-watch/lib/watch.js:104:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

函数使用 SpringBoot。函数通过 `java -jar` 命令在本地正常运行，`fun build && fun deploy` 部署后也能正常访问

相关配置：
```yml
Properties:
        Handler: index.handler
        Runtime: custom
        CodeUri: ./
```

bootstrap：
```sh
#!/usr/bin/env bash
export PORT=9000
java -jar -Dserver.port=$PORT -Dspring.profiles.active=prod target/user-service-1.0.jar
```

**Comment by coco-super** [comment]
@CloudyAnt 感觉您的项目不需要 fun build ，尝试将 .fun 目录删掉。在项目根目录下打包编译，本地调试，部署。

**Comment by coco-super** [comment]
#926

**Comment by coco-super** [comment]
@CloudyAnt 先 close 掉，有问题请提新的 issue。
